name: Code Quality Check # 工作流名称 

on:
  push: # 触发条件：每次代码 push 到仓库时自动运行 
    branches: [ main ] # 监控 main 分支的 push 事件 

jobs:
  code-check:
    runs-on: ubuntu-latest # 使用最新版 Ubuntu 运行环境 
    
    steps:
      - name: Checkout code # 步骤1：拉取代码 
        uses: actions/checkout@v4

      - name: Set up JDK 17 # 步骤2：配置 Java 环境 
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven' # 启用 Maven 依赖缓存加速构建 

      - name: Code Static Analysis # 步骤3：代码静态检查 
        run: |
          # 使用 Maven 插件执行代码质量检查 
          mvn checkstyle:check # Checkstyle 代码规范检查 
          mvn pmd:check        # PMD 静态代码分析 
          mvn spotbugs:check   # SpotBugs 潜在 Bug 检测 

      - name: Run Tests # 步骤4：执行单元测试 
        run: mvn test # 运行所有单元测试，确保功能健壮性

      - name: Code Coverage # 步骤5：代码覆盖率检查（可选）
        run: mvn jacoco:report # 生成 JaCoCo 覆盖率报告 